export const stations = {
  victoria: {
    victoria: [
      "Walthamstow Central",
      "Blackhorse Road",
      "Tottenham Hale",
      "Seven Sisters",
      "Finsbury Park",
      "Highbury & Islington",
      "King's Cross St. Pancras",
      "Euston",
      "Warren Street",
      "Oxford Circus",
      "Green Park",
      "Victoria",
      "Pimlico",
      "Vauxhall",
      "Stockwell",
      "Brixton",
    ],
  },
  jubilee: [
    "Stanmore",
    "Canons Park",
    "Queensbury",
    "Kingsbury",
    "Wembley Park",
    "Neasden",
    "Dollis Hill",
    "Willesden Green",
    "Kilburn",
    "West Hampstead",
    "Finchley Road",
    "Swiss Cottage",
    "St. Johns Wood",
    "Baker Street",
    "Bond Street",
    "Green Park",
    "Westminster",
    "Waterloo",
    "Southwark",
    "London Bridge",
    "Bermondsey",
    "Canada Water",
    "Canary Wharf",
    "North Greenwich",
    "Canning Town",
    "West Ham",
    "Stratford",
  ],
  central: [
    "Ealing",
    "West Acton",
    "North Acton",
    "East Acton",
    "White City",
    "Shepherd's Bush",
    "Holland Park",
    "Notting Hill",
    "Queensway",
    "Lancaster Gate",
    "Marble Arch",
    "Bond Street",
    "Oxford Circus",
    "Tottenham Court",
    "Holborn",
    "Chancery",
    "St. Paul's",
    "Bank",
    "Liverpool Street",
    "Bethnal Green",
    "Mile End",
    "Stratford",
    "Leyton",
    "LeytonStone",
    "Snaresbrook",
    "South Woodford",
    "Woodford",
    "Buckhurst Hill",
    "Loughton",
    "Debden",
    "Theydon",
    "Epping",
  ],
  metropolitan: [
    "Amersham",
    "Chalfont",
    "Chorleywood",
    "Rickmansworth",
    "Moor Park",
    "Northwood",
    "Northwood Hills",
    "Pinner",
    "North Harrow",
    "Harrow-on-the-Hill",
    "Northwick Park",
    "Preston Road",
    "Wembley Park",
    "Willesden Green",
    "Finchley Road",
    "Baker Street",
    "Great Portland Street",
    "Euston Square",
    "King's Cross",
    "Farringdon",
    "Barbican",
    "Moorgate",
    "Liverpool Street",
    "Aldgate",
  ],
  // northern: ["London Bridge", "Waterloo", "Charing Cross", "Camden Town"],
  // bakerloo: ["Baker Street", "Oxford Circus", "Piccadilly Circus", "Charing Cross"],
  // piccadilly: ["Earl's Court", "South Kensington", "Piccadilly Circus", "Leicester Square", "Covent Garden"],
  // district: ["Notting Hill Gate", "South Kensington", "Westminster", "Tower Hill"]
};
